# SPDX-License-Identifier: GPL-2.0-only
# Makefile for Qualcomm CAMSS Offline Processing Engine (OPE) driver

qcom-camss-ope-objs := \
		core.o \
		pipeline.o \
		params.o

obj-$(CONFIG_VIDEO_QCOM_CAMSS_OPE) += qcom-camss-ope.o
